//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetHeader
    {
        public BudgetHeader()
        {
            this.BudgetLineItems = new HashSet<BudgetLineItem>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<BudgetLineItem> BudgetLineItems { get; set; }
    }
}
