//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.RegisterLineItems = new HashSet<RegisterLineItem>();
            this.BudgetLineItems = new HashSet<BudgetLineItem>();
            this.CreditCardTransactions = new HashSet<CreditCardTransaction>();
            this.RegisterLineItemDetails = new HashSet<RegisterLineItemDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RegisterLineItem> RegisterLineItems { get; set; }
        public virtual ICollection<BudgetLineItem> BudgetLineItems { get; set; }
        public virtual ICollection<CreditCardTransaction> CreditCardTransactions { get; set; }
        public virtual ICollection<RegisterLineItemDetail> RegisterLineItemDetails { get; set; }
    }
}
