//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardTransaction
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
        public int RegisterLineItemID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual RegisterLineItem RegisterLineItem { get; set; }
    }
}
