//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryHeader
    {
        public EntryHeader()
        {
            this.EntryDetails = new HashSet<EntryDetail>();
        }
    
        public int EntryHeaderID { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Comments { get; set; }
        public int TypeofEntry { get; set; }
    
        public virtual ICollection<EntryDetail> EntryDetails { get; set; }
    }
}
