//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoneyManagerEntities : DbContext
    {
        public MoneyManagerEntities()
            : base("name=MoneyManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetHeader> BudgetHeaders { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CreditCardTransaction> CreditCardTransactions { get; set; }
        public virtual DbSet<RegisterLineItemDetail> RegisterLineItemDetails { get; set; }
        public virtual DbSet<RegisterLineItem> RegisterLineItems { get; set; }
        public virtual DbSet<BudgetLineItem> BudgetLineItems { get; set; }
    }
}
