//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterLineItem
    {
        public RegisterLineItem()
        {
            this.RegisterLineItemDetails = new HashSet<RegisterLineItemDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public bool IsCleared { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<RegisterLineItemDetail> RegisterLineItemDetails { get; set; }
    }
}
